# Choose the name you want
name: Publish

on:
  push:
    branches:
      - main
  # Leave if you want to trigger builds manually
  workflow_dispatch:

jobs:

  publish:
    uses: sebnozzi/minimicro-actions/.github/workflows/itch-deploy.yaml@main
    with:
      minidisk_main_file: main.ms
      minidisk_additional_entries: >-
        *
      boot_opts_path: bootOpts.grfon
      custom_executable_name: micro-hack.exe
      itch_io_username: treytomes
      itch_io_game_id: micro-hack
      itchio_web_channel: html5
    secrets:
      itch_io_api_key: ${{ secrets.ITCH_IO_API_KEY }}
